### ISSUE TITLE
Can't login: certificate verify failed (Faraday::Error::ConnectionFailed)

### ISSUE THREAD

**Issue by fzaninotto** [cloudapp/cloudapp.rb#34]
```
> ruby --version
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin12.3.0]
> cloudapp --version
2.1.0
> cloudapp test.png
Email: [myemail]
Password (typing will be hidden): [mypassword]
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::Error::ConnectionFailed)
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1126:in `get'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/faraday-0.8.1/lib/faraday/adapter/net_http.rb:70:in `perform_request'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/faraday-0.8.1/lib/faraday/adapter/net_http.rb:35:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/faraday-0.8.1/lib/faraday/response/logger.rb:20:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/service_middleware.rb:14:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/faraday-0.8.1/lib/faraday/connection.rb:226:in `run_request'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/request.rb:59:in `submit'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/request.rb:85:in `submit_and_wait'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/service.rb:68:in `perform_request'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/service.rb:52:in `block (2 levels) in <module:Service>'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/leadlight-0.1.0/lib/leadlight/service.rb:32:in `root'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/lib/cloudapp/service.rb:44:in `token_for_account'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/lib/cloudapp/service.rb:40:in `token_for_account'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/bin/cloudapp:22:in `token_for_account'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/bin/cloudapp:47:in `authenticate'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/bin/cloudapp:128:in `share'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cloudapp-2.1.0/bin/cloudapp:150:in `<top (required)>'
    from /usr/local/opt/ruby/bin/cloudapp:23:in `load'
    from /usr/local/opt/ruby/bin/cloudapp:23:in `<main>'
```

**Comment by lmarburger** [comment]
Since I don't have permissions to unassign myself, mind unassigning me?
